### ISSUE TITLE
v2 이전

### ISSUE THREAD

**Issue by 3boku** [yeololi/Sumrov#31]
# v2이전해도됨?

## 일단 카카오톡 기능(Next Auth)만 v1에서 토요일까지 ㄱㄱ
[카카오톡 이거 보고 공부하세요 1번](https://github.com/Hyunseos-studyroom/go/blob/main/kakao/README.md) (백엔드 통신용)
[카카오톡 이거 보고 공부하세요 2번](https://www.youtube.com/watch?v=EqpJTFP1pHw) (Next Auth)
[카카오톡 이거 보고 공부하세요 3번](https://www.youtube.com/watch?v=iWQEK8pS2kU) (Supabase)

## v2 이전 계획
next폴더만 빼내서 새 레포팔게

정현서가 할 수 있는 것들!
1. 국재윤이 해줘야 하는 것 빼고 모두

국재윤이 v2에서 해줘야 하는 것
1. 카카오톡 토요일까지 하니까 인가코드만 백엔드로 넘겨주셈
2. 유저가 저장되어 있는 클러스터 접근 권한 or 안에 있는 데이터들 싹 넘겨주셈

## 정현서가 토요일까지 끝낼 수 있는 것
1. GET product요청 (shop이 product로 바뀜)
2. GET notice요청
4. POST SignUp 요청 (후에 바로 Login 되게끔도 가능)
5. POST Login 요청
6. GET Logout 요청
7. GET OrderList

**Comment by 3boku** [comment]
@igiza1213 빠른 Approve는 뽀뽀해드림

**Comment by 3boku** [comment]
@igiza1213 폰으로 리뷰할 수 있는거 다 안다 빨리 comment 달아라.

**Comment by igiza1213** [comment]
LGTM
ASAP으로 진행해드리죠
